version: '3.8'

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - "27017:27017" # Expose port to host
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - common_network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081" # Access Mongo Express on localhost:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - common_network

  node-app:
    build:
      context: . # Build from your Dockerfile
    environment:
      MONGO_URL: mongodb://admin:password@mongodb:27017 # Connect to MongoDB service by container name
    networks:
      - common_network
    depends_on:
      - mongodb
    ports:
      - "3000:3000" # Expose Node.js app on port 3000

networks:
  common_network:
    driver: bridge
    external: true # Make sure this external network exists
